spring:
  application:
    name: user

server:
  port: 8888

say-hello:
  ribbon:
    eureka:
      enabled: true
    listOfServers: localhost:8083,localhost:8082
    ServerListRefreshInterval: 15000
